#ifndef MODEL_DATA_H
#define MODEL_DATA_H

// TODO: REPLACE THIS FILE WITH YOUR TRAINED MODEL
// 
// This is a placeholder header file. After training your bark detection model,
// you must replace this file with the actual model data generated by the
// convert_to_tflite.py script (see TRAINING.md).
//
// The training process will generate a proper model_data.h file that contains:
// - extern const unsigned char g_model_data[];
// - extern const int g_model_data_len;
//
// Steps to add your trained model:
// 1. Follow the complete training guide in TRAINING.md
// 2. Train your model using the provided Python scripts
// 3. Run convert_to_tflite.py to generate model_data.h
// 4. Replace this file with the generated model_data.h
// 5. Uncomment the #define below
// 6. Rebuild and flash your firmware
//
// Until you provide your trained model, the bark detector will not initialize.

// Uncomment this line after you've replaced this file with your trained model:
// #define BARK_DETECTOR_MODEL_DATA_AVAILABLE

#ifdef BARK_DETECTOR_MODEL_DATA_AVAILABLE

// This is where your actual model data will be defined
// Example format (your actual model will be much larger):
//
// alignas(16) const unsigned char g_model_data[] = {
//     0x1c, 0x00, 0x00, 0x00, 0x54, 0x46, 0x4c, 0x33,
//     // ... thousands more bytes ...
// };
// const int g_model_data_len = sizeof(g_model_data);

extern const unsigned char g_model_data[];
extern const int g_model_data_len;

#else

// Placeholder empty data (will cause initialization to fail with clear error message)
const unsigned char g_model_data[] = {0};
const int g_model_data_len = 0;

#endif // BARK_DETECTOR_MODEL_DATA_AVAILABLE

#endif // MODEL_DATA_H
