#ifndef MODEL_DATA_H
#define MODEL_DATA_H

// ============================================================================
// IMPORTANT: REPLACE THIS FILE WITH YOUR TRAINED MODEL
// ============================================================================
// 
// This is a PLACEHOLDER header file. The bark detector WILL NOT WORK until
// you train your own model and replace this file!
//
// After training your bark detection model, you must replace this entire file
// with the actual model data generated by convert_to_tflite.py (see TRAINING.md).
//
// The generated model_data.h file will automatically contain:
// - #define BARK_DETECTOR_MODEL_DATA_AVAILABLE
// - alignas(16) const unsigned char g_model_data[] = { ... model bytes ... };
// - const int g_model_data_len = ...;
//
// Steps to add your trained model:
// 1. Follow the complete training guide in TRAINING.md
// 2. Train your model using the provided Python scripts
// 3. Run convert_to_tflite.py to generate a new model_data.h
// 4. REPLACE THIS ENTIRE FILE with the generated model_data.h
// 5. Rebuild and flash your firmware
//
// Until you complete these steps, bark detector initialization will fail with
// a clear error message directing you to TRAINING.md
//
// DO NOT manually uncomment the #define below - the generated file will have
// it uncommented automatically.
// ============================================================================

// This flag is INTENTIONALLY commented out in the placeholder
// The generated model_data.h will have it uncommented automatically
// #define BARK_DETECTOR_MODEL_DATA_AVAILABLE

#ifdef BARK_DETECTOR_MODEL_DATA_AVAILABLE

// This is where your actual model data will be defined
// Example format (your actual model will be much larger):
//
// alignas(16) const unsigned char g_model_data[] = {
//     0x1c, 0x00, 0x00, 0x00, 0x54, 0x46, 0x4c, 0x33,
//     // ... thousands more bytes ...
// };
// const int g_model_data_len = sizeof(g_model_data);

extern const unsigned char g_model_data[];
extern const int g_model_data_len;

#else

// Placeholder empty data (will cause initialization to fail with clear error message)
const unsigned char g_model_data[] = {0};
const int g_model_data_len = 0;

#endif // BARK_DETECTOR_MODEL_DATA_AVAILABLE

#endif // MODEL_DATA_H
